@extends('layouts.main')

@php
    $sectionTitle = 'Conservation';
    $bread = [[$sectionTitle, '#' . $sectionTitle]];
@endphp

@section('hero')
    <x-main.hero :list="$bread"></x-main.hero>
@endsection

@section('content')
    <div main="wrapper">
        <input mobile-nav-section="toggle" id="mobile-nav-section" type="checkbox" class="hide-off-canvas">
        <div tripnav-section="wrapper" js-tripnav-section-wrapper="" hide="lg+">
            <x-main.mobile-breadcrumb :list="$bread"></x-main.mobile-breadcrumb>
            <label tripnav-section="bar" for="mobile-nav-section">
                <div tripnav-section="hamburger"><span tripnav-section="icon"></span></div>
            </label>
        </div>
        {{-- SUBPAGE WRAPPER --}}
        <main subpage="wrapper subpage">
            <div subpage="middle">
                <div name="wrapper" enso="">
                    <h1>
                        {{ $site_name }} is the world's first 100% carbon-neutral travel company, and we continue to
                        provide
                        leadership to the travel industry.
                    </h1>
                </div>
                <div content="wrapper" enso=""><strong>The Carbon Problem&nbsp;</strong><br>
                    Did you know travel-related activities account for approximately 10% percent of worldwide greenhouse gas
                    emissions that contribute to climate change? Or that a long-haul flight generates more carbon emissions
                    than an average person in many countries generates in an entire year? Even a round-trip flight from New
                    York to California emits more CO2 than your car produces in a year. And more people are flying more
                    often. There’s no way around it: travel emits a lot of carbon. That’s why we’re doing all we can to
                    offset the emissions that are generated by our adventures.<br>
                    <br>
                    <strong>We are Industry Leaders in Carbon Reduction<br>
                    </strong>Through our carbon pollution reduction program, we’ve made pioneering strides in the travel
                    industry. Since 2007, Natural Habitat Adventures has been <strong>the world's first 100% carbon-neutral
                        travel company</strong>. We embarked on that ambitious project in partnership with Sustainable
                    Travel International, reducing and offsetting the carbon emissions that result from all office- and
                    trip-related activities. In 2018, we began partnering with <a href="https://www.southpole.com/">South
                        Pole</a>,&nbsp;a sustainability company that works with businesses and governments to reduce carbon
                    impacts by offsetting greenhouse gas emissions via third-party verified projects around the world. In
                    2019, we took our commitment to a whole new level: we also offset all our travelers' flights to and from
                    our global adventure destinations, increasing the total amount of our carbon offsetting by 300-400%.<br>
                    <br>
                    <strong>How It Works<br>
                    </strong>We calculate the carbon emitted from activities on your adventure (the majority of these
                    emissions result from burning fossil fuels for transportation). Then, we fund <a
                        href="#conservation/carbon-neutral-travel/carbon-offset-projects/">carbon
                        reduction projects</a> to balance emissions in an amount equal to what is released on our trips and
                    via our guests’ transportation to and from our adventures. For example, we support renewable geothermal
                    and hydroelectric energy in Sumatra, Indonesia, and we provide high-efficiency cook stoves in Ethiopia
                    to replace the burning of wood. <br>
                    <br>
                    <strong>Innovative Strides</strong><br>
                    Since 2022, {{ $site_name }} has supported <a href="https://www.tomorrowsair.com/">Tomorrow’s
                        Air</a>,&nbsp;a
                    carbon removal collective funding innovative negative-emissions technologies while also promoting
                    climate-conscious travel through education and storytelling.&nbsp;Negative emissions technologies can
                    help clean up carbon dioxide from the atmosphere fast via direct air capture, biochar and enhanced
                    weathering. These progressive technology lock carbon away in rocks, soils, plants and aquifers for
                    long-term storage. While nature provides its own carbon removal solutions, these technologies have the
                    potential to remove tens of billions of tons of CO2 per year, enabling the rapid, massive removal
                    required to address climate change.<br>
                    <br>
                    <strong>What Difference Does It Make?&nbsp;</strong><br>
                    From January 1, 2007 through present day, we have offset&nbsp;68,093&nbsp;tons of carbon dioxide.
                    According to the <a href="https://www.epa.gov/energy/greenhouse-gas-equivalencies-calculator"
                        target="_blank">U.S. Environmental Protection Agency</a>, this is equivalent to:
                    <ul>
                        <li>14,672 cars not on the road for a year</li>
                        <li>169,020,823 gallons of gasoline not consumed</li>
                        <li>157,650 barrels of oil not consumed</li>
                        <li>8,577 homes not using electricity for one year</li>
                        <li>1,125,924 tree seedlings grown for 10 years</li>
                        <li>459 acres of woodlands preserved from deforestation</li>
                        <li>2,947,449 trash bags of waste recycled instead of landfilled</li>
                    </ul>
                    <p><strong><br>
                            You Can Offset Your Personal Travel, Too</strong><br>
                        If you’d like to offset you flights for trips other than with {{ $site_name }}, navigate to <a
                            href="https://market.southpole.com/individual" target="_blank">this handy carbon calculator</a>
                        on South Pole's website, which lets you calculate and offset your emissions at the same time. It
                        doesn’t cost much, but the collective impact is significant!</p>
                </div>
            </div>

            <div trip-name-vert="wrapper 1">
                <div trip-name-vert="sticky">
                    {{ $sectionTitle }}
                </div>
            </div>
        </main>
    </div>
@endsection
